import React from "react"
import './food.css';

const Food = () =>

<food class="page-food">
<div class="container">
  <div class="row">
    <div class="col l6 s12">
      
      <img id="top" src="top.png" alt="">
      <div id="form_container">
  
        <h1><a>Untitled Form</a></h1>
        <form id="form_70679" class="appnitro" enctype="multipart/form-data" method="post" action="">
        <div class="form_description">
        <h2>Untitled Form</h2>
        <p>This is your form description. Click here to edit.</p>
      </div>            
      <ul >
      
          <li id="li_5" >
    <label class="description" for="element_5">Drop Down </label>
    <div>
    <select class="element select medium" id="element_5" name="element_5"> 
      <option value="" selected="selected"></option>
<option value="1" >First option</option>
<option value="2" >Second option</option>
<option value="3" >Third option</option>

    </select>
    </div> 
    </li>   <li id="li_1" >
    <label class="description" for="element_1">Text </label>
    <div>
      <input id="element_1" name="element_1" class="element text medium" type="text" maxlength="255" value=""/> 
    </div> 
    </li>   <li id="li_2" >
    <label class="description" for="element_2">Paragraph </label>
    <div>
      <textarea id="element_2" name="element_2" class="element textarea medium"></textarea> 
    </div> 
    </li>   <li id="li_3" >
    <label class="description" for="element_3">Price </label>
    <span class="symbol">$</span>
    <span>
      <input id="element_3_1" name="element_3_1" class="element text currency" size="10" value="" type="text" /> .    
      <label for="element_3_1">Dollars</label>
    </span>
    <span>
      <input id="element_3_2" name="element_3_2" class="element text" size="2" maxlength="2" value="" type="text" />
      <label for="element_3_2">Cents</label>
    </span>
     
    </li>   <li id="li_6" >
    <label class="description" for="element_6">Checkboxes </label>
    <span>
      <input id="element_6_1" name="element_6_1" class="element checkbox" type="checkbox" value="1" />
<label class="choice" for="element_6_1">First option</label>
<input id="element_6_2" name="element_6_2" class="element checkbox" type="checkbox" value="1" />
<label class="choice" for="element_6_2">Second option</label>
<input id="element_6_3" name="element_6_3" class="element checkbox" type="checkbox" value="1" />
<label class="choice" for="element_6_3">Third option</label>

    </span> 
    </li>   <li id="li_4" >
    <label class="description" for="element_4">Upload a File </label>
    <div>
      <input id="element_4" name="element_4" class="element file" type="file"/> 
    </div>  
    </li>
      
          <li class="buttons">
          <input type="hidden" name="form_id" value="70679" />
          
        <input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
    </li>
      </ul>
    </form> 
    <div id="footer">
      Generated by <a href="http://www.phpform.org">pForm</a>
    </div>
  </div>
  <img id="bottom" src="bottom.png" alt="">

    </div>
  </div>
</div>
</food>

export default Food;